
# 橋 bridge properties

spring:
  
  # Turn off the Spring Boot banner.
  main: 
    banner-mode: 'off' 

  datasource: 
    #
    # JDBC connection properties:
    #
    url: jdbc:mysql://localhost:3306/db_bridge
    username: bridgeuser
    password: H*wF1=53szsMCBd?.FC&

  jpa:
    properties:
      hibernate:
        '[format_sql]': true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              #
              # Generate the database schema:
              # 
              # https://www.baeldung.com/spring-data-jpa-generate-db-schema
              # 
              action: update # [create] or [update]
              create-target: db_scripts/update.sql # [create] or [update]
       
logging:
  level:
    org:
      hibernate:
        SQL: trace # Log JDBC SQL statements. debug or trace
        orm:
          jdbc:
            bind: trace # Log JDBC SQL statements.
      springframework:
        jdbc:
          core: trace # Log JDBC SQL statements.
          
# Spring Security bebug (very usefull):          
#        security: debug

# Reduce logging level:
#    root: warn 

