
# 橋 bridge properties

spring:
  
  # Turn off the Spring Boot banner.
  main: 
    banner-mode: 'off' 

  datasource: 
    #
    # JDBC connection properties:
    #
    url: jdbc:mysql://localhost:3306/db_bridge
    username: bridgeuser
    password: H*wF1=53szsMCBd?.FC&

  jpa:
    # spring.jpa.open-in-view
    # https://backendhance.com/en/blog/2023/open-session-in-view/
    # https://www.youtube.com/watch?v=g9yspLxwEH4 
    open-in-view: false 
    properties:
      hibernate:
        '[format_sql]': true # Maior legibilidade para o script de schema gerado.
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              #
              # Generate the database schema:
              # 
              # https://www.baeldung.com/spring-data-jpa-generate-db-schema
              # 
              # action: create # [create] or [update]
              # create-target: db_scripts/create.sql # [create] or [update]
      
# Log JDBC SQL statements with bind values.
# Se tirar o do 'springframework' perde o log do String Security.
# Se tirar o do 'hibernate' perde o log do JpaRepository.       
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
      hibernate:
        SQL: DEBUG
          
# Spring Security bebug (very usefull):          
#        security: debug

# Reduce logging level:
    root: warn 

# --- FIM ---        